##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$


windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size 800 500

windowrule = match:class ^(org.pulseaudio.pavucontrol)$, move (monitor_w-806) 35

windowrule = tile on, pseudo on, size 1600 900, match:class ^(steam)$

windowrule = pseudo on, match:title ^(Steam)$

windowrule {
    name = eye-break-logic
    match:initial_class = ^(eye-break)$
    float = on
    center = on
    size = 325 210
}

windowrule {
    name = file-progress-center
    match:title = ^(File Operation Progress)$
    float = on
    size = 500 150
    center = on
}
